version: '3.7'

services:
    chrome:
        image: selenium/node-chrome:latest
        shm_size: 2gb
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
            - SE_NODE_SESSION_TIMEOUT=500
            - SE_NODE_MAX_SESSIONS=3
        deploy:
            replicas: 4
        entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

    edge:
        image: selenium/node-edge:latest
        shm_size: 2gb
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
            - SE_NODE_SESSION_TIMEOUT=500
            - SE_NODE_MAX_SESSIONS=3
        deploy:
            replicas: 4
        entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

    firefox:
        image: selenium/node-firefox:latest
        shm_size: 2gb
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
            - SE_NODE_SESSION_TIMEOUT=500
            - SE_NODE_MAX_SESSIONS=3
        deploy:
            replicas: 4
        entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

    selenium-hub:
        image: selenium/hub:latest
        container_name: selenium-hub
        restart: always
        ports:
            - "4442:4442"
            - "4443:4443"
            - "4444:4444"
